# permissions for end users to edit migritors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: migritor-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: migrator
    app.kubernetes.io/part-of: migrator
    app.kubernetes.io/managed-by: kustomize
  name: migritor-editor-role
rules:
- apiGroups:
  - cache.eurecom.com
  resources:
  - migritors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.eurecom.com
  resources:
  - migritors/status
  verbs:
  - get
