---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - cache.eurecom.com
  resources:
  - migritors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.eurecom.com
  resources:
  - migritors/finalizers
  verbs:
  - update
- apiGroups:
  - cache.eurecom.com
  resources:
  - migritors/status
  verbs:
  - get
  - patch
  - update
