apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: migrator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Migritor is the Schema for the migritors API
      displayName: Migritor
      kind: Migritor
      name: migritors.cache.eurecom.com
      version: v1alpha1
  description: checkpoint, build push operators to a remote registry
  displayName: migrator-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - checkpoint
  - build
  - push
  links:
  - name: Migrator
    url: https://migrator.domain
  maturity: alpha
  provider:
    name: migrator-operator
    url: https://github.com/abdelghanimeliani/migrator_operator
  version: 0.0.0
